### PR TITLE
StackTraceParser: Made methods overridable

### PR DESCRIPTION
**Pull request by LazyTarget**
Made methods in StackTraceParser overridable, to enable extensibility

### CODE REVIEW

**Comment by christiango** [comment]
We tend to favor composition over inheritance for extensibility. Is it possible for you to provide your own IStackTraceParser implementation that uses an instance StackTraceParser to provide the customizations you are looking for?

**Comment by LazyTarget** [comment]
I get what you mean.

The thing is that I only want to make some minor changes to the `TryExtractMethodNameFromFrame`
method, which is private.

For this, it is either required to make an complete new implementation of the parser or copy the code and make adjustments locally or like you say implement a new implementation which uses the default class as a fallback. In this case that would mean having to handle value migration between the result instances.

Also this solution would but all logic on the client application. Where as the library implementation is more trusted, documented, used and tested.

An example for this pull request is my other one: https://github.com/microsoft/sourcemap-toolkit/pull/81
For a small addition to an added syntax, I should not have to copy the whole solution to make my modifications. At least I believe so?

**Comment by christiango** [comment]
So the private methods of that class are intentionally not part of the API for this class, we don't intend for them to be used outside this class. Future changes to the library will likely break your custom behavior. That private method might disappear or get completely rewritten.

Extension by inheritance is not something I think will scale, since every consumer of the library that wants custom behavior would have to insert a bunch of virtual modifiers throughout the code base. 

I'll merge the PR since I don't think this will have any negative affects to the library itself, but just wanted to make my concerns for your customization clear.

**Comment by LazyTarget** [comment]
> So the private methods of that class are intentionally not part of the API for this class, we don't intend for them to be used outside this class. **Future changes to the library will likely break your custom behavior. That private method might disappear or get completely rewritten.**

Yes, and in this case I am OK with this:
- As most breaking changes mostly involve minor method updates like renaming or adding arguments. 
- I also can protect myself by writing my own unit tests and ensuring that my updated parser keeps with my expected behavior.
- I can also opt out of from updating when there are breaking changes


Is there any specific release plan for the NuGet package?

**Comment by christiango** [comment]
Regarding the NuGet package, unfortunately there is not a plan to get publishing back online. I no longer work on the team that used this package and we don't have anyone else maintaining it.

**Pull request merged**
